wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725344224.0
    t:
      1:
      - 1
      - 55
      3:
      - 14
      - 23
      4: 3.10.14
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
role:
  desc: null
  value: validator
specs:
  desc: null
  value:
    cpu:
      count: 4
      frequency: 1449.948625
    gpu:
      count: 1
      details:
      - name: NVIDIA GeForce MX130
        capacity: 2048
      capacity: 2048
      memory_speed: 405
      graphics_speed: 135
    ram:
      free: 616722432
      used: 5155577856
      total: 8057057280
      available: 2143854592
      swap_free: 2183929856
      swap_used: 2111033344
      read_speed: 1066.132537562307
      swap_total: 4294963200
      write_speed: 9961.534259589122
    hard_disk:
      free: 837198204928
      used: 95071305728
      total: 982240026624
      read_speed: 1071.1204067613087
      write_speed: 1182.6334102149112
    has_docker: true
config:
  desc: null
  value:
    ssh:
      port: 4444
      __is_set: {}
    config: null
    netuid: 15
    strict: false
    __is_set:
      netuid: true
      wallet.name: true
      logging.debug: true
      wallet.hotkey: true
      subtensor.network: true
    no_prompt: false
    subtensor:
      _mock: false
      network: test
      __is_set: {}
      chain_endpoint: wss://entrypoint-finney.opentensor.ai:443
    auto_update: true
    blacklist_hotkeys: []
    whitelist_hotkeys: []
    blacklist_coldkeys: []
    miner_hashcat_path: hashcat
    whitelist_coldkeys: []
    no_version_checking: false
    blacklist_exploiters: true
    whitelist_unrecognized: false
    force_update_prometheus: false
    validator_specs_batch_size: 64
    miner_whitelist_not_updated: false
    miner_hashcat_extended_options: ''
    miner_hashcat_workload_profile: '3'
    validator_challenge_batch_size: 256
    miner_whitelist_not_enough_stake: false
    validator_perform_hardware_query: true
    miner_whitelist_updated_threshold: 60
    validator_whitelist_updated_threshold: 60
hotkey:
  desc: null
  value: 5EAYwTkVUR3KCGQ3JPGaqD6e2qsiBwe41peyUtt5wrXF2xGr
allocated:
  desc: null
  value: null
signature:
  desc: null
  value: 64f621f8f88423a0ccbffe576494055c01ff397171832036a91855c393a14b52f534c4dad043a190ba3f0e9c8af59382ec76454e5c71fc46eddd68736f90a98b
allocated_hotkeys:
  desc: null
  value: []
