wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725020289.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 5
      - 14
      - 17
      - 23
      - 62
      4: 3.10.14
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
role:
  desc: null
  value: validator
specs:
  desc: null
  value:
    cpu:
      count: 4
      frequency: 3490.9825
    gpu:
      count: 1
      details:
      - name: NVIDIA GeForce MX130
        capacity: 2048
      capacity: 2048
      memory_speed: 405
      graphics_speed: 135
    ram:
      free: 1495457792
      used: 4271910912
      total: 8057044992
      available: 2813034496
      swap_free: 2019016704
      swap_used: 2275946496
      read_speed: 2899.0613638562877
      swap_total: 4294963200
      write_speed: 26974.750787832018
    hard_disk:
      free: 836091482112
      used: 96178028544
      total: 982240026624
      read_speed: 2686.469348671274
      write_speed: 2778.4943957179576
    has_docker: true
config:
  desc: null
  value:
    __is_set:
      netuid: true
      subtensor.network: true
      wallet.name: true
      wallet.hotkey: true
      axon.port: true
      logging.debug: true
    netuid: 15
    auto_update: true
    blacklist_exploiters: true
    blacklist_hotkeys: []
    blacklist_coldkeys: []
    whitelist_hotkeys: []
    whitelist_coldkeys: []
    whitelist_unrecognized: false
    validator_perform_hardware_query: true
    validator_challenge_batch_size: 256
    validator_specs_batch_size: 64
    force_update_prometheus: false
    validator_whitelist_updated_threshold: 60
    miner_hashcat_path: hashcat
    miner_hashcat_workload_profile: '3'
    miner_hashcat_extended_options: ''
    miner_whitelist_not_enough_stake: false
    miner_whitelist_not_updated: false
    miner_whitelist_updated_threshold: 60
    ssh:
      __is_set: {}
      port: 4444
    subtensor:
      __is_set: {}
      network: test
      chain_endpoint: wss://entrypoint-finney.opentensor.ai:443
      _mock: false
    no_prompt: false
    config: null
    strict: false
    no_version_checking: false
hotkey:
  desc: null
  value: 5EAYwTkVUR3KCGQ3JPGaqD6e2qsiBwe41peyUtt5wrXF2xGr
allocated:
  desc: null
  value: 5EAYwTkVUR3KCGQ3JPGaqD6e2qsiBwe41peyUtt5wrXF2xGr
signature:
  desc: null
  value: 2217b9447e7bd98272fad006253e6d92d14e32a2a049c7c96958a43950f27d5a68e192ef47119c451adad20fe21b77ac0ff91e1de7d32e6573027950951d4583
