wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725016864.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 5
      - 14
      - 17
      - 23
      - 62
      4: 3.10.14
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
role:
  desc: null
  value: miner
specs:
  desc: null
  value:
    cpu:
      count: 4
      frequency: 3404.308375
    gpu:
      count: 1
      capacity: 2048.0
      details:
      - name: NVIDIA GeForce MX130
        capacity: 2048.0
      graphics_speed: 135
      memory_speed: 405
    hard_disk:
      total: 982240026624
      free: 836115988480
      used: 96153522176
      write_speed: 2832.4007482290335
      read_speed: 2542.927125015157
    ram:
      total: 8057044992
      available: 2661605376
      used: 4408913920
      free: 517287936
      swap_total: 4294963200
      swap_used: 1977020416
      swap_free: 2317942784
      read_speed: 2996.1240365452063
      write_speed: 29074.61527797033
    has_docker: true
config:
  desc: null
  value:
    __is_set:
      netuid: true
      subtensor.network: true
      wallet.name: true
      wallet.hotkey: true
      axon.port: true
      axon.ip: true
      logging.debug: true
      auto_update: true
    netuid: 15
    auto_update: true
    blacklist_exploiters: true
    blacklist_hotkeys: []
    blacklist_coldkeys: []
    whitelist_hotkeys: []
    whitelist_coldkeys: []
    whitelist_unrecognized: false
    validator_perform_hardware_query: true
    validator_challenge_batch_size: 256
    validator_specs_batch_size: 64
    force_update_prometheus: false
    validator_whitelist_updated_threshold: 60
    miner_hashcat_path: hashcat
    miner_hashcat_workload_profile: '3'
    miner_hashcat_extended_options: ''
    miner_whitelist_not_enough_stake: false
    miner_whitelist_not_updated: false
    miner_whitelist_updated_threshold: 60
    ssh:
      __is_set: {}
      port: 4444
    subtensor:
      __is_set: {}
      network: test
      chain_endpoint: wss://entrypoint-finney.opentensor.ai:443
      _mock: false
    no_prompt: false
    config: null
    strict: false
    no_version_checking: false
hotkey:
  desc: null
  value: 5EAYwTkVUR3KCGQ3JPGaqD6e2qsiBwe41peyUtt5wrXF2xGr
allocated:
  desc: null
  value: 5EAYwTkVUR3KCGQ3JPGaqD6e2qsiBwe41peyUtt5wrXF2xGr
signature:
  desc: null
  value: dad9c8cd3231ce83f449417d195f19906d32e90841a0f1b765350d39a2ee2b7bcb85acd97a4df756741641a922fa12f74b1dcce8f0efd55052fc11f8d762c083
