wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725022205.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 5
      - 14
      - 17
      - 23
      - 62
      4: 3.10.14
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
role:
  desc: null
  value: miner
specs:
  desc: null
  value:
    cpu:
      count: 4
      frequency: 3603.4571250000004
    gpu:
      count: 1
      capacity: 2048.0
      details:
      - name: NVIDIA GeForce MX130
        capacity: 2048.0
      graphics_speed: 135
      memory_speed: 405
    hard_disk:
      total: 982240026624
      free: 836105678848
      used: 96163831808
      write_speed: 2680.3233536760713
      read_speed: 2443.407239977164
    ram:
      total: 8057044992
      available: 2666364928
      used: 4512944128
      free: 936644608
      swap_total: 4294963200
      swap_used: 2164764672
      swap_free: 2130198528
      read_speed: 2821.1225828148645
      write_speed: 25559.439366240098
    has_docker: true
config:
  desc: null
  value:
    __is_set:
      netuid: true
      subtensor.network: true
      wallet.name: true
      wallet.hotkey: true
      axon.port: true
      axon.ip: true
    netuid: 15
    auto_update: true
    blacklist_exploiters: true
    blacklist_hotkeys: []
    blacklist_coldkeys: []
    whitelist_hotkeys: []
    whitelist_coldkeys: []
    whitelist_unrecognized: false
    validator_perform_hardware_query: true
    validator_challenge_batch_size: 256
    validator_specs_batch_size: 64
    force_update_prometheus: false
    validator_whitelist_updated_threshold: 60
    miner_hashcat_path: hashcat
    miner_hashcat_workload_profile: '3'
    miner_hashcat_extended_options: ''
    miner_whitelist_not_enough_stake: false
    miner_whitelist_not_updated: false
    miner_whitelist_updated_threshold: 60
    ssh:
      __is_set: {}
      port: 4444
    subtensor:
      __is_set: {}
      network: test
      chain_endpoint: wss://entrypoint-finney.opentensor.ai:443
      _mock: false
    no_prompt: false
    config: null
    strict: false
    no_version_checking: false
hotkey:
  desc: null
  value: 5EAYwTkVUR3KCGQ3JPGaqD6e2qsiBwe41peyUtt5wrXF2xGr
allocated:
  desc: null
  value: null
signature:
  desc: null
  value: 62fb24b520735243d76e54d11be261aa80eba8e9e94bf89817c8995ed815fa2b6ce4a471be5df7f863f1e65bc1d5c5bf7443ec24a76a1b15b93d83134dff8f83
allocated_hotkeys:
  desc: null
  value:
  - 5EAYwTkVUR3KCGQ3JPGaqD6e2qsiBwe41peyUtt5wrXF2xGr
