wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725343683.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 5
      - 14
      - 17
      - 23
      - 62
      4: 3.10.14
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
role:
  desc: null
  value: validator
specs:
  desc: null
  value:
    cpu:
      count: 4
      frequency: 1600.3613750000002
    gpu:
      count: 1
      details:
      - name: NVIDIA GeForce MX130
        capacity: 2048
      capacity: 2048
      memory_speed: 405
      graphics_speed: 135
    ram:
      free: 379715584
      used: 5140811776
      total: 8057057280
      available: 2123837440
      swap_free: 2499039232
      swap_used: 1795923968
      read_speed: 1142.364091949014
      swap_total: 4294963200
      write_speed: 9536.410349688507
    hard_disk:
      free: 837201969152
      used: 95067541504
      total: 982240026624
      read_speed: 687.7114510250159
      write_speed: 460.4985847886186
    has_docker: true
config:
  desc: null
  value:
    __is_set:
      netuid: true
      subtensor.network: true
      wallet.name: true
      wallet.hotkey: true
      logging.debug: true
    netuid: 15
    auto_update: true
    blacklist_exploiters: true
    blacklist_hotkeys: []
    blacklist_coldkeys: []
    whitelist_hotkeys: []
    whitelist_coldkeys: []
    whitelist_unrecognized: false
    validator_perform_hardware_query: true
    validator_challenge_batch_size: 256
    validator_specs_batch_size: 64
    force_update_prometheus: false
    validator_whitelist_updated_threshold: 60
    miner_hashcat_path: hashcat
    miner_hashcat_workload_profile: '3'
    miner_hashcat_extended_options: ''
    miner_whitelist_not_enough_stake: false
    miner_whitelist_not_updated: false
    miner_whitelist_updated_threshold: 60
    ssh:
      __is_set: {}
      port: 4444
    subtensor:
      __is_set: {}
      network: test
      chain_endpoint: wss://entrypoint-finney.opentensor.ai:443
      _mock: false
    no_prompt: false
    config: null
    strict: false
    no_version_checking: false
hotkey:
  desc: null
  value: 5EAYwTkVUR3KCGQ3JPGaqD6e2qsiBwe41peyUtt5wrXF2xGr
allocated:
  desc: null
  value: null
signature:
  desc: null
  value: ba773f349aea691f49fd6786b297eeabc5bb53fdafba918b573723a4a46e2e437c97dc9933e263e5abd68694bce79ad7b5b2d500f1772b5aaf5ab8969455df89
allocated_hotkeys:
  desc: null
  value:
  - 5EAYwTkVUR3KCGQ3JPGaqD6e2qsiBwe41peyUtt5wrXF2xGr
